import { Metadata } from "next";
import dynamic from "next/dynamic";
import {
  bannerCatsApi,
  newArrivalsApi,
  productSaleApi,
  sellingsProductApi,
  slideBannerApi,
  topBandsApi,
} from "../_service/common";

const Banner = dynamic(() => import("../components/home/Banner"));
const FlashSale = dynamic(() => import("../components/home/FlashSale"));
const SlideBanner = dynamic(() => import("../components/home/SlideBanner"));
const TopBrands = dynamic(() => import("../components/home/TopBrands"));
const OnSellingProducts = dynamic(
  () => import("../components/home/OnSellingProducts")
);
const NewArrivals = dynamic(() => import("../components/home/NewArrivals"));

export const metadata: Metadata = {
  title: "Perfoment NextJS",
  description: "Generated by create next app",
};

export default async function Home() {
  const [
    productSale,
    bannerCats,
    slideBanner,
    topBands,
    sellingsProduct,
    newArrivals,
  ] = await Promise.all([
    productSaleApi(),
    bannerCatsApi(),
    slideBannerApi(),
    topBandsApi(),
    sellingsProductApi(),
    newArrivalsApi(),
  ]);
  return (
    <>
      <Banner items={bannerCats} />
      <FlashSale products={productSale} />
      <SlideBanner slideBanner={slideBanner} />
      <TopBrands topBands={topBands} />
      <OnSellingProducts product={sellingsProduct} />
      <NewArrivals items={newArrivals} />
    </>
  );
}
