import { Metadata, ResolvingMetadata } from "next";
import dynamic from "next/dynamic";
import {
  bannerCatsApi,
  newArrivalsApi,
  productSaleApi,
  sellingsProductApi,
  slideBannerApi,
  topBandsApi,
} from "../_service/common";
import { LOCALE_PAGE } from "../_contants/locale.contant";
import { METADATA_SEO } from "../_contants/metadata.contant";

const Banner = dynamic(() => import("../components/home/Banner"));
const FlashSale = dynamic(() => import("../components/home/FlashSale"));
const SlideBanner = dynamic(() => import("../components/home/SlideBanner"));
const TopBrands = dynamic(() => import("../components/home/TopBrands"));
const OnSellingProducts = dynamic(
  () => import("../components/home/OnSellingProducts")
);
const NewArrivals = dynamic(() => import("../components/home/NewArrivals"));

type Props = {
  params: Promise<{ locale: string }>;
  searchParams: Promise<{ [key: string]: string | string[] | undefined }>;
};

export async function generateMetadata(
  { params }: Props,
  parent: ResolvingMetadata
): Promise<Metadata> {
  // read route params
  const locale = (await params).locale;

  // optionally access and extend (rather than replace) parent metadata
  const previousImages = (await parent).openGraph?.images || [];

  return {
    title:
      locale === LOCALE_PAGE.EN
        ? METADATA_SEO.EN.HOME.TITLE
        : METADATA_SEO.VI.HOME.TITLE,
    description:
      locale === LOCALE_PAGE.EN
        ? METADATA_SEO.EN.HOME.DESCRIPTION
        : METADATA_SEO.VI.HOME.DESCRIPTION,
    openGraph: {
      images: ["/some-specific-page-image.jpg", ...previousImages],
    },
  };
}

// export const metadata: Metadata = {
//   title: "Perfoment NextJS",
//   description: "Generated by create next app",

// };

export default async function Home() {
  const [
    productSale,
    bannerCats,
    slideBanner,
    topBands,
    sellingsProduct,
    newArrivals,
  ] = await Promise.all([
    productSaleApi(),
    bannerCatsApi(),
    slideBannerApi(),
    topBandsApi(),
    sellingsProductApi(),
    newArrivalsApi(),
  ]);
  return (
    <>
      <Banner items={bannerCats} />
      <FlashSale products={productSale} />
      <SlideBanner slideBanner={slideBanner} />
      <TopBrands topBands={topBands} />
      <OnSellingProducts product={sellingsProduct} />
      <NewArrivals items={newArrivals} />
    </>
  );
}
